disabled_rules: # rule identifiers to exclude from running
- colon
- large_tuple
- function_body_length
- identifier_name
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- Xcode Templates
- xCode Templates
- movsTests
- R.generated.swift

identifier_name:
    excluded:
        - id
trailing_whitespace:
    ignores_empty_lines: true
    ignores_comments: true
