# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movs' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movs

  pod 'SnapKit', '~> 4.0.0'
  pod 'Swinject'
  pod 'Moya/RxSwift', '~> 12.0'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'SwiftLint'
  
  target 'MovsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
